spring:
  application:
    name: eureka-server
  profiles.active: local
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${spring.application.name}:${vcap.application.instance_index:${server.port}}
  enableSelfPreservation: false
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
logging:
  level:
    com.netflix: WARN
    org.springframework.cloud: WARN
---
spring:
  profiles: local
eureka:
  client:
     serviceUrl:
       defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: ${PORT:8761}   
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80  
#server:
#  port: ${vcap.application.port:80}
--- 
